source("load_data.R")
source("load_data_20-22.R")
source("Join_Entries.R")
source("xgBoost_modeling.R")
run = function() {
  pbp_17 = load_eh_pbp(2017, 2018)
  pbp_20 = load_eh_pbp(2020, 2021)
  pbp_21 = load_eh_pbp(2021, 2022)
  pbp = pbp_17 %>% rbind(pbp_20) %>% rbind(pbp_21)
  load_sznajder_game_reports(pbp, 2017, 2022)
  zone_entries = read_csv("zone_entries_current.csv")
  zone_exits = read_csv("zone_exits_current.csv")
  big_join = join_entries(data, zone_entries, zone_exits)
  faceoffs_full = condition(big_join)
}